### ISSUE TITLE
Setup is unclear

### ISSUE THREAD

**Issue by rgaudin** [kiwix/borg-backup#11]
README says it's using bitwarden and borgbase but there's no explanation about how it uses them nor how to setup.

```
docker run -d -v <barckupdir>:/storage \
       -e BW_EMAIL=<your_bitwarden_login_mail> \
       -e BW_PASSWORD=<your_bitwarden_master_password> \
       -e BORGBASE_NAME=test_borg \
       -e BORGBASE_KEY=<borgbase_api_token> \
       -ti backup-docker
```

BW email and password are easy to understand but what about `BORGBASE_NAME`. Is it a borgbase *repository* name? Should it already exist or will it be created?
The `BORGBASE_KEY` is a borgbase token but which kind should be created? _Read-only_, *Create-only*, _Full Access_ ?

**Comment by rgaudin** [comment]
Should maybe include instructions to tweak bitwarden notifications as current setup sends a `New Device Logged In From Linux` each time the container is run

**Comment by kelson42** [comment]
Pretty much linked to #10. For BorgBase the only thing the user should take care is the `master` BorgBase credentials (and they can not be given here as ENV variable).

**Comment by florentk** [comment]
duplicate with #28
