### ISSUE TITLE
Error in borg archive name

### ISSUE THREAD

**Issue by rgaudin** [kiwix/borg-backup#12]
Formatting error in borgmatic template
https://github.com/kiwix/borg-backup/blob/cbdb1eeff0d908ff8fc1995767a41848901d2075/bin/init_borgbase_repository.py#L107

Should be `{now}`.

**Comment by florentk** [comment]
@rgaudin No, `{now}` must be in borgmatic file config.

**Comment by rgaudin** [comment]
OK then
