### ISSUE TITLE
Don't require master bitwarden password

### ISSUE THREAD

**Issue by rgaudin** [kiwix/borg-backup#2]
Current implementation requires the master credentials of the bitwarden account for every backup.

We need to separate the *sub-account*/*token* creation process so that the backup is launched using limited credentials

**Comment by kelson42** [comment]
@florentk This is pretty important and centric.

**Comment by florentk** [comment]
@rgaudin Practically, we must to give the possibility of providing the session key instead of the login/password ? I don't see how to do otherwise.

**Comment by kelson42** [comment]
@florentk what is te proble exactly? Which par is problmatic in the doc I have furnished?

**Comment by florentk** [comment]
@kelson42 to create/get bitwarden items, I use the [CLI](https://bitwarden.com/help/article/cli/), and with this CLI I need a session key that I get with email/password login.

**Comment by kelson42** [comment]
@florentk You should access the Bitwarden API with the token, is that what you mean?

**Comment by florentk** [comment]
@kelson42 the Bitwarden API is only for manage organisation, not to get item saved in Bitwarden.

**Comment by florentk** [comment]
it seems that asking a new login if access denied, solves the problem, @rgaudin,  what do you think?

**Comment by rgaudin** [comment]
None of your messages are clear :)
Looking at the BW cli documentation, it seems that there is no such thing as a token.

- a SESSION_KEY can be obtained using the email and master password
- SESSION_KEY is used as a token to perform all the actions we want (get/set objects)
- SESSION_KEY only works on a previously logged-in *enverionment*. I think `login` fetch/sync the vault and then the session works locally. 
- SESSION_KEY doesn't appear to expire with cli (unless you logout)

So we can't just use it as a token.

Something that might be possible to overcome this is to create and use individual accounts for all *clients*. All of them would be added to the *Kiwix* organization which holds the shared keys.
@florentk what do you think ? Would that even be possible? I haven't used the org feature of BW yet.

**Comment by florentk** [comment]
@rgaudin @kelson42 
> Something that might be possible to overcome this is to create and use individual accounts for all _clients_. All of them would be added to the _Kiwix_ organization which holds the shared keys.

Yes, that's the way to do it. I simple secure process :

- Init the backup with a BW individual account called _master_. 
- _master_ create an organization
- Add an other individual account, called _bakcuper_ , to the organization
- Share the key in read only mode with the organisation member
- Lauch the backup with BW _bakcuper_ account

**Comment by kelson42** [comment]
@florentk I don't think this can work, because the container needs to save many things setup during the setup in the Bitwarden and the full control over these data should be at the `master` level.

**Comment by rgaudin** [comment]
Bon, je réponds en français cette fois :)
Pour faire suite à la discussion avec @kelson42:

* effectivement il n'y a pas de token *classique* donc on va utiliser un deuxieme compte (attention on écrit `backuper`)
* on a besoin d'une organisation pour pouvoir partager des éléments et gérer les permissions dessus
* en mode backup, le container doit avoir des env relatives à son backup (un ID de repo par exemple). L'outil doit vérifier le fonctionnement du repo bien sûr (et récupérer sa clef borgbase sur BW) et en cas d'échec, indiquer clairement qu'il ne peut pas continuer et que c'est probablement dû a un repo non setupé ou une clé manquante sur BW.
* l'outils doit offir une autre commande pour le setup d'un *repo*/backup (à faire une seule fois). Cet outil sera dans l'image mais sera un mini CLI interactif qui demandera l'acces au compte et password master de BW pour pouvoir récupérer les infos borgbase et créer/partager tout ce qui doit l'être.

```sh
$ docker run kiwix/borg-backup:latest setup-new-repo --name cardshop
blabla, enter BW master email: xxxx@kiwix.org
blavlabla, enter BW master password: ******************
Logged-in successfuly, creating…
```

À noter, il existe un module [bitwarden](https://pypi.org/project/bitwarden/) pour python ; potentiellement plus solide à utiliser que le binaire CLI (si utilisé dans le python!)

Il existe aussi une [API Publique](https://bitwarden.com/help/article/public-api/) (qui est utilisée par le cli et le module). Je ne suis pas sûr qu'elle soit particulierement utile dans notre cas de figure mais il sera bien de vérifier. À noter que l'API fourni bien un token classique… mais limité à 1h. [bon apparement on peut pas l'utiliser sur l'offre Free]

**Comment by florentk** [comment]
> À noter, il existe un module [bitwarden](https://pypi.org/project/bitwarden/) pour python ; potentiellement plus solide à utiliser que le binaire CLI (si utilisé dans le python!)
> 
J'avais testé, mais elle est plus maintenu, impossible de l'installer.

> Il existe aussi une [API Publique](https://bitwarden.com/help/article/public-api/) (qui est utilisée par le cli et le module). Je ne suis pas sûr qu'elle soit particulierement utile dans notre cas de figure mais il sera bien de vérifier. À noter que l'API fourni bien un token classique… mais limité à 1h. [bon apparement on peut pas l'utiliser sur l'offre Free]

Comme j'ai dit dans le précedent commentaire, cette API petmet uniquement de gérer les membres d'une organisation, pas pour l'enregistrement d'un identifiant.

C'est donc pour ça que je me suis reporté sur le CLI, à ma grande déception.
