### ISSUE TITLE
check if repo exist with name already used

### ISSUE THREAD

**Issue by florentk** [kiwix/borg-backup#29]
While the setup, if a repo exist with name already used, what to do ? ask removing ? stop the setup ? use existing ?

**Comment by rgaudin** [comment]
Good question.
IMO, we should not ask or attempt to delete the repo. There's too much potential for damage and that would require a full-access token that we don't want to require.

Using existing would mean checking that there's no SSH key for appendOnly and only in that case we could continue. I don't think it's worth the effort.

I think we should stop the setup (failing) but with a clear explanation:
- repo already exists.
- if you want to use this tool with an existing repo, configure bitwarden manually.
- if it shouldn't exist, go delete it manually

Obviously, that means our setup process should not fail after creating the repo 🙃
