### ISSUE TITLE
Setup-new-repo is too fragile

### ISSUE THREAD

**Issue by rgaudin** [kiwix/borg-backup#32]
I keep on getting errors when trying to setup a new repo. Sometimes the 5 retries is just not enough.

I think we should understand the root cause of this: is this because borgbase needs a bit of time to set stuff up?

The consequence is when this happens, we've already sent SSH keypairs to bitwarden and created the repo on borgbase. So relaunching the same command may succeed but enventually, the backup step would fail because there are now multiple items for this repo in bitwarden. This requires manually connecting to bitwarden UI to remove them.
Alternative is to use a different repo name but then one have to manually delete the previous one from borgbase UI as the number of repo is limited.

**Comment by rgaudin** [comment]
Had to increase it to 2mn (120s) to setup my repo…

**Comment by florentk** [comment]
@rgaudin Would it be okay if we delete the repo that was just created after all failed attempts ?

**Comment by rgaudin** [comment]
I wasn't sure what you meant until I saw the PR. Your take is that if we can't initialize borgmatic, we should delete the borgbase repo and start over…

I don't think it's the proper way to handle that. We should be clear about what's happening and allow a reasonnable duration before attempting to connect and retry with maybe increased delays…

That said, I am against deleting the repo on failure as we specifically ask users to use Create-Only tokens on borgbase which doesn't allow deleting repos (fortunately!). In case of failure for which we think the solution is to remove the repo, we should simply ask user to do so manually.

**Comment by florentk** [comment]
@rgaudin ok, i don't know what to do

**Comment by rgaudin** [comment]
1. Print that we're waiting a bit for borgbase to create repo (write duration)
1. Wait a bit
1. Try
1. If it fails, increase delay and redo until attempt are exhausted
