### ISSUE TITLE
Document repo name restrictions

### ISSUE THREAD

**Issue by rgaudin** [kiwix/borg-backup#38]
We store SSH keypairs (and borgabse API token) into bitwarden on individual items named after the borgbase repo name.

So if the repo is named `mysql`, we create a `mysql` item in the vault/collection.

When retrieving this item on future runs, we use the `--search` feature of bitwarden cli's `list` command (there is no exact name matching).

This means that for this `mysql` repo, we'll search for `mysql`. If there are multiple items matching `mysql` (say `mysql` and `mysql2`), then the process stops because it can't find a single result.

It's important we communicate that limitation on the documentation so users use non-clashing repo names.

**Comment by kelson42** [comment]
@rgaudin I believe the setup should detect & stop if collision detected. With the documentation we should encourage users to use FQDN (if possible) in the repo name or otherwise secure the uniqueness of the identifier.

**Comment by rgaudin** [comment]
Ah yes, I didn't think of that but we could indeed check on setup and not allow such a creation.
