### ISSUE TITLE
Better arguments management

### ISSUE THREAD

**Issue by rgaudin** [kiwix/borg-backup#43]
Not a priority obviously but the way arguments are processed currently leave room for typos as there is no such thing as *unexpected* param so `-alert-days 3` for instance (missing `-`) doesn't raise anything and just uses the default value.

**Comment by florentk** [comment]
@rgaudin  I think that this issue is fixed in 4ba1668c2e882aaebcd76210b56bed5d551c56c1

**Comment by rgaudin** [comment]
Agrees
