### ISSUE TITLE
Deploy borg-backup

### ISSUE THREAD

**Issue by kelson42** [kiwix/borg-backup#44]
Everywhere where is is necessary

**Comment by rgaudin** [comment]
Please list this everywhere other it's not much usable

**Comment by florentk** [comment]
@rgaudin @kelson42  Currently, we can't deploy borg-backup on Sloppy, because we can't share volume. 

https://kb.sloppy.io/en/articles/922928-volumes

**Comment by kelson42** [comment]
Considering that we can not share access to volumes on Sloppy, this should be deployed for:
* stats 
* mirrorbrain (in particular the db)

**Comment by florentk** [comment]
@kelson42 done with :  
https://github.com/kiwix/maintenance/commit/d2790e279135a155dc57ab4297c967f1341b0c25
https://github.com/kiwix/maintenance/commit/bec24923cea8dc27529cd2bb0c592e14c532718b

but we have a problem avec mysqldump : https://github.com/kiwix/maintenance/issues/156

**Comment by florentk** [comment]
done with https://github.com/kiwix/borg-backup/issues/56
