### ISSUE TITLE
You are not logged in error during backup process

### ISSUE THREAD

**Issue by gregology** [kiwix/borg-backup#73]
Hey Team, I'm having authentication errors when trying to run backups. The Setting up stage seems to work. It has created a Borgbase repo and the read only Bitwarden user has access to the ssh-ed25519 key etc. However, when I try and run the backup it attempts to log in multiple times before failing. I have double checked the password, removed any special characters, and tried with and without double quotes (it's 64 characters long, is there a possible issue using a long password?). 

```
$ docker run -v /dir/to/backup:/storage:ro \
>     -e BITWARDEN_EMAIL="readonly@email.com" \
>     -e BITWARDEN_PASSWORD="readonly-password" \
>     kiwix/borg-backup backup --name backup_name --every 1h
Start initialization ...
Could not find dir, "/root/.config/Bitwarden CLI"; creating it instead.
Could not find data file, "/root/.config/Bitwarden CLI/data.json"; creating it instead.
You are not logged in.? client_id: Please try again ...
You are not logged in.? client_id: Please try again ...
You are not logged in.? client_id: Please try again ...
You are not logged in.? client_id: Please try again ...
You are not logged in.? client_id: Please try again ...
Unable to log in your Bitwarden account. Please check your credentials.
```

Any ideas what I'm doing wrong? Did I miss read something? Cheers Team!

**Comment by gregology** [comment]
I worked it out, the documentation on Docker Hub is outdated. I needed to include `BW_CLIENTID`, `BW_CLIENTSECRET`, and `BW_PASSWORD` during the backup stage.

**Comment by rgaudin** [comment]
This is dependent on https://github.com/openzim/docker-publish-action/issues/2 We can leave this open until this feature is implemented
