### ISSUE TITLE
Allow for env file to specify tables to skip

### ISSUE THREAD

**Issue by audiodude** [kiwix/borg-backup#79]
For WP1, we will have a very large (~50GB) table of data that is largely disposable. That is, it can easily be re-created completely in less than a day and contains no user data.

We would like to exclude this table from our database backups.

It seems that borgmatic supports an `options` key for MySQL/MariaDB databases (https://torsion.org/borgmatic/docs/how-to/backup-your-databases/#database-dump-hooks), and we can specify `--ignore-table=wp1.too_large_table`. So all we need is an env option like `IGNORE_TABLES=name1,name2,name3` that will be passed through to the borgmatic config.

**Comment by audiodude** [comment]
@benoit74

**Comment by rgaudin** [comment]
@kelson42 what's the prio on this?

**Comment by kelson42** [comment]
@rgaudin If possible on your end, would be great to do right now so @audiodude and @benoit74 can continue to implement the DRP properly for WP1

**Comment by rgaudin** [comment]
Done ; tested. Use `DATABASES_OPTIONS` to pass any option to mysqldump.

Example for a MariaDB:

```
-e DATABASES_OPTIONS="--ignore-table=cardshop.manager_organization --ignore-table=cardshop.manager_configuration --ignore-table=cardshop.manager_order --no-data"
```
