### ISSUE TITLE
Bitwarden to require 2FA

### ISSUE THREAD

**Issue by rgaudin** [kiwix/borg-backup#80]
Just received the following:

![Image](https://github.com/user-attachments/assets/046be4cd-72a9-4a96-82bb-39070bb6399b)

It looks like borg-backup will soon stop working because it relies on user+password sign-in and each call is a fresh new one without cookie (we receive multiple notifications about this daily).

We need to assess the consequences and fix this **very soon**. There is no date on BW website about when this will be applied.

**Comment by kelson42** [comment]
Bitworden has developed itself to propose secret mgmt features, we should look in that direction IMHO.

**Comment by benoit74** [comment]
I sent a support case to BW to ask them to clarify impact of two-step login on CLI tools (which we are using currently)

**Comment by benoit74** [comment]
In fact, I read documentation too fast. Everything is at https://bitwarden.com/help/cli/

It looks like two-step login is only going to be required when we login with email/password, not when we login with API key (client id / client secret). If I'm not mistaken, we do login with API key.

**Comment by kelson42** [comment]
@benoit74 Thx for checking this, just FYI - if we have a problem - here is the page about Bitwarden Secret Manager https://bitwarden.com/products/secrets-manager/ (in opposition to Bitwarden Password Manager)

**Comment by rgaudin** [comment]
That's right, we log-in with API Key and use the password to unlock the vault.
I am closing this as there is not short-term risk but in the long-term it would probably be more solid to rely on API rather than CLI. Bitwarden has greatly improved its [toolset](https://bitwarden.com/developers/)
